### ISSUE TITLE
Does not work with Meteor 1.3

### ISSUE THREAD

**Issue by mikepaszkiewicz** [255kb/cordova-keyboard#1]
Error thrown on build 'hackishlyHidesInputView' when running an iOS device build, conflict with ionic keyboard. #

**Comment by janjackson** [comment]
+1 same here with meteor 1.5, can't build for iOS :(

**Comment by 255kb** [comment]
This plugin is very old and I am not working with Meteor anymore since some time. 
So I will probably not fix this any time soon. Feel free to submit a pull request if you have any clue why it's not working.
